format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$time
$character\
"""
add_newline = true
# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#33D17A #ffffff"
style_root = "bg:#33D17A #ff0000"
format = '[ $user ]($style)'
disabled = false

[hostname]
#style = "bg:#171421 #ffffff"
style = "#ffffff"
ssh_only = false
format = '[ @$hostname ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "#white"
disabled = true # Disabled by default

[directory]
style = "bg:#ffffff #000000"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "#5ffdff"
format = '[ $symbol $branch]($style)'

[git_status]
style = "#5ffdff"
modified = "+"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#ff76ff"
format = '[ ♥ $time ]($style)'
